name: pull-request-check
on:
  pull_request:
    paths:
      - hedgedocs/**
      - mkdocs.yml
    branches: 
      - main

env:
  ENABLE_GIT_PLUGINS: False

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-git-committers-plugin-2
      - run: mkdocs build -s -v
